import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LeftSidebar from "@/components/LeftSidebar";
import Advertisements from "@/components/Advertisements";
import MobileTopbar from "@/components/MobileTopbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Sport Tv",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col md:flex-row`}
      >
        <LeftSidebar />
        <div className="w-full py-[50px] px-5 md:px-[50px]">
          <div className=" max-w-[1200px] mx-auto flex flex-row gap-4 md:gap-[30px] min-h-screen">
            {children}
            <Advertisements />
          </div>
        </div>
      </body>
    </html>
  );
}
